apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-pod
spec:
  containers:
    - name: result-app-pod
      image: dockersamples/eamplevotingapp_result
      ports:
        - containerPort: 80
