apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-pod
spec:
  containers:
    - name: voting-app-pod
      image: dockersamples/eamplevotingapp_vote
      ports:
        - containerPort: 80
