apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-pod
spec:
  containers:
    - name: worker-app-pod
      image: dockersamples/eamplevotingapp_worker
